export const enum EventTypes {
    LOGIN = "LOGIN",
    DELETE = "DELETE",
    REFRESH = "REFRESH",
    DELETE_FILE = "DELETE_FILE",
    UPLOAD = "UPLOAD",
    UPLOAD_TO_DB = "UPLOAD_TO_DB",
    FETCH_FILE = "FETCH_FILE",
    UPLOAD_SIGNED = "UPLOAD_SIGNED",
    ACTION_LOADING = "ACTION_LOADING",
    ACTION_FINISHED = "ACTION_FINISHED"
}